import type {
  Company,
  Developer,
  HasSkillRelationship,
  Project,
  Skill,
  SkillRelatedToRelationship,
  Technology,
  TechnologyRelatedToRelationship,
  UsesRelationship,
  WorkedAtRelationship,
  WorkedOnRelationship,
} from './types'

export const companies: Company[] = [
  { id: 'company-acme', name: 'Acme Corp', industry: 'Software' },
  { id: 'company-globex', name: 'Globex', industry: 'Finance' },
  { id: 'company-initech', name: 'Initech', industry: 'Enterprise Software' },
  { id: 'company-umbrella', name: 'Umbrella Analytics', industry: 'Healthcare' },
  { id: 'company-nimbus', name: 'Nimbus Cloud Systems', industry: 'Cloud Infrastructure' },
]

export const technologies: Technology[] = [
  { id: 'tech-typescript', name: 'TypeScript', category: 'Language' },
  { id: 'tech-python', name: 'Python', category: 'Language' },
  { id: 'tech-react', name: 'React', category: 'Framework' },
  { id: 'tech-nextjs', name: 'Next.js', category: 'Framework' },
  { id: 'tech-nodejs', name: 'Node.js', category: 'Runtime' },
  { id: 'tech-neo4j', name: 'Neo4j', category: 'Database' },
  { id: 'tech-postgresql', name: 'PostgreSQL', category: 'Database' },
  { id: 'tech-aws', name: 'AWS', category: 'Cloud' },
  { id: 'tech-docker', name: 'Docker', category: 'Infrastructure' },
  { id: 'tech-graphql', name: 'GraphQL', category: 'API' },
]

export const skills: Skill[] = [
  { id: 'skill-frontend-dev', name: 'Frontend Development', category: 'Frontend' },
  { id: 'skill-backend-dev', name: 'Backend Development', category: 'Backend' },
  { id: 'skill-graph-databases', name: 'Graph Databases', category: 'Data' },
  { id: 'skill-api-design', name: 'API Design', category: 'Backend' },
  { id: 'skill-cloud-architecture', name: 'Cloud Architecture', category: 'Cloud' },
  { id: 'skill-data-modeling', name: 'Data Modeling', category: 'Data' },
  { id: 'skill-machine-learning', name: 'Machine Learning', category: 'Data' },
  { id: 'skill-devops', name: 'DevOps', category: 'Cloud' },
  { id: 'skill-ui-ux', name: 'UI/UX Design', category: 'Design' },
  { id: 'skill-system-design', name: 'System Design', category: 'Backend' },
]

export const projects: Project[] = [
  {
    id: 'project-devgraph',
    name: 'DevGraph',
    description: 'Graph-powered developer intelligence platform',
    status: 'active',
  },
  {
    id: 'project-payflow',
    name: 'PayFlow',
    description: 'Payment processing platform',
    status: 'completed',
  },
  {
    id: 'project-healthsync',
    name: 'HealthSync',
    description: 'Patient data synchronization service',
    status: 'active',
  },
  {
    id: 'project-marketpulse',
    name: 'MarketPulse',
    description: 'Real-time market analytics dashboard',
    status: 'on-hold',
  },
  {
    id: 'project-shoplite',
    name: 'ShopLite',
    description: 'Lightweight e-commerce storefront',
    status: 'completed',
  },
  {
    id: 'project-fleettrack',
    name: 'FleetTrack',
    description: 'Real-time logistics fleet tracking dashboard',
    status: 'active',
  },
  {
    id: 'project-eduspark',
    name: 'EduSpark',
    description: 'Online learning platform for K-12 students',
    status: 'active',
  },
  {
    id: 'project-billwise',
    name: 'BillWise',
    description: 'Automated invoicing and billing system',
    status: 'completed',
  },
]

export const developers: Developer[] = [
  {
    id: 'dev-alice',
    name: 'Alice Nguyen',
    email: 'alice.nguyen@example.com',
    location: 'San Francisco, CA',
    experience: 7,
  },
  {
    id: 'dev-brian',
    name: 'Brian Okafor',
    email: 'brian.okafor@example.com',
    location: 'Austin, TX',
    experience: 4,
  },
  {
    id: 'dev-carla',
    name: 'Carla Silva',
    email: 'carla.silva@example.com',
    location: 'Lisbon, Portugal',
    experience: 9,
  },
  {
    id: 'dev-david',
    name: 'David Kim',
    email: 'david.kim@example.com',
    location: 'Seoul, South Korea',
    experience: 3,
  },
  {
    id: 'dev-elena',
    name: 'Elena Petrova',
    email: 'elena.petrova@example.com',
    location: 'Berlin, Germany',
    experience: 6,
  },
  {
    id: 'dev-farah',
    name: 'Farah Haddad',
    email: 'farah.haddad@example.com',
    location: 'Dubai, UAE',
    experience: 5,
  },
  {
    id: 'dev-gabriel',
    name: 'Gabriel Santos',
    email: 'gabriel.santos@example.com',
    location: 'São Paulo, Brazil',
    experience: 8,
  },
  {
    id: 'dev-hana',
    name: 'Hana Kobayashi',
    email: 'hana.kobayashi@example.com',
    location: 'Tokyo, Japan',
    experience: 4,
  },
  {
    id: 'dev-isabella',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@example.com',
    location: 'Milan, Italy',
    experience: 6,
  },
  {
    id: 'dev-jamal',
    name: 'Jamal Carter',
    email: 'jamal.carter@example.com',
    location: 'Atlanta, GA',
    experience: 2,
  },
  {
    id: 'dev-kavya',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@example.com',
    location: 'Bangalore, India',
    experience: 5,
  },
  {
    id: 'dev-liam',
    name: "Liam O'Connor",
    email: 'liam.oconnor@example.com',
    location: 'Dublin, Ireland',
    experience: 10,
  },
  {
    id: 'dev-maya',
    name: 'Maya Cohen',
    email: 'maya.cohen@example.com',
    location: 'Tel Aviv, Israel',
    experience: 7,
  },
  {
    id: 'dev-noah',
    name: 'Noah Fischer',
    email: 'noah.fischer@example.com',
    location: 'Munich, Germany',
    experience: 3,
  },
  {
    id: 'dev-olivia',
    name: 'Olivia Chen',
    email: 'olivia.chen@example.com',
    location: 'Toronto, Canada',
    experience: 9,
  },
]

export const hasSkillRelationships: HasSkillRelationship[] = [
  { developerId: 'dev-alice', skillId: 'skill-frontend-dev', proficiency: 'expert', yearsOfExperience: 7 },
  { developerId: 'dev-alice', skillId: 'skill-ui-ux', proficiency: 'advanced', yearsOfExperience: 5 },
  { developerId: 'dev-alice', skillId: 'skill-api-design', proficiency: 'intermediate', yearsOfExperience: 3 },
  { developerId: 'dev-brian', skillId: 'skill-backend-dev', proficiency: 'advanced', yearsOfExperience: 4 },
  { developerId: 'dev-brian', skillId: 'skill-devops', proficiency: 'intermediate', yearsOfExperience: 2 },
  { developerId: 'dev-carla', skillId: 'skill-graph-databases', proficiency: 'expert', yearsOfExperience: 8 },
  { developerId: 'dev-carla', skillId: 'skill-data-modeling', proficiency: 'expert', yearsOfExperience: 9 },
  { developerId: 'dev-carla', skillId: 'skill-system-design', proficiency: 'advanced', yearsOfExperience: 6 },
  { developerId: 'dev-david', skillId: 'skill-machine-learning', proficiency: 'intermediate', yearsOfExperience: 3 },
  { developerId: 'dev-david', skillId: 'skill-backend-dev', proficiency: 'beginner', yearsOfExperience: 1 },
  { developerId: 'dev-elena', skillId: 'skill-cloud-architecture', proficiency: 'expert', yearsOfExperience: 6 },
  { developerId: 'dev-elena', skillId: 'skill-devops', proficiency: 'advanced', yearsOfExperience: 5 },
  { developerId: 'dev-farah', skillId: 'skill-api-design', proficiency: 'advanced', yearsOfExperience: 5 },
  { developerId: 'dev-farah', skillId: 'skill-backend-dev', proficiency: 'intermediate', yearsOfExperience: 4 },
  { developerId: 'dev-gabriel', skillId: 'skill-system-design', proficiency: 'expert', yearsOfExperience: 8 },
  { developerId: 'dev-gabriel', skillId: 'skill-backend-dev', proficiency: 'advanced', yearsOfExperience: 7 },
  { developerId: 'dev-hana', skillId: 'skill-ui-ux', proficiency: 'advanced', yearsOfExperience: 4 },
  { developerId: 'dev-hana', skillId: 'skill-frontend-dev', proficiency: 'intermediate', yearsOfExperience: 3 },
  { developerId: 'dev-isabella', skillId: 'skill-data-modeling', proficiency: 'advanced', yearsOfExperience: 6 },
  { developerId: 'dev-isabella', skillId: 'skill-machine-learning', proficiency: 'intermediate', yearsOfExperience: 3 },
  { developerId: 'dev-jamal', skillId: 'skill-frontend-dev', proficiency: 'beginner', yearsOfExperience: 2 },
  { developerId: 'dev-kavya', skillId: 'skill-cloud-architecture', proficiency: 'advanced', yearsOfExperience: 5 },
  { developerId: 'dev-kavya', skillId: 'skill-devops', proficiency: 'intermediate', yearsOfExperience: 4 },
  { developerId: 'dev-liam', skillId: 'skill-system-design', proficiency: 'expert', yearsOfExperience: 10 },
  { developerId: 'dev-liam', skillId: 'skill-backend-dev', proficiency: 'expert', yearsOfExperience: 9 },
  { developerId: 'dev-liam', skillId: 'skill-graph-databases', proficiency: 'advanced', yearsOfExperience: 6 },
  { developerId: 'dev-maya', skillId: 'skill-machine-learning', proficiency: 'expert', yearsOfExperience: 7 },
  { developerId: 'dev-maya', skillId: 'skill-data-modeling', proficiency: 'advanced', yearsOfExperience: 6 },
  { developerId: 'dev-noah', skillId: 'skill-devops', proficiency: 'intermediate', yearsOfExperience: 3 },
  { developerId: 'dev-noah', skillId: 'skill-backend-dev', proficiency: 'beginner', yearsOfExperience: 2 },
  { developerId: 'dev-olivia', skillId: 'skill-cloud-architecture', proficiency: 'expert', yearsOfExperience: 9 },
  { developerId: 'dev-olivia', skillId: 'skill-system-design', proficiency: 'advanced', yearsOfExperience: 7 },
]

export const workedOnRelationships: WorkedOnRelationship[] = [
  { developerId: 'dev-alice', projectId: 'project-devgraph', role: 'Frontend Lead', startDate: '2023-01-15', endDate: null },
  { developerId: 'dev-alice', projectId: 'project-shoplite', role: 'Frontend Engineer', startDate: '2021-03-01', endDate: '2022-11-30' },
  { developerId: 'dev-brian', projectId: 'project-payflow', role: 'Backend Engineer', startDate: '2022-06-01', endDate: '2023-05-01' },
  { developerId: 'dev-brian', projectId: 'project-devgraph', role: 'Backend Engineer', startDate: '2023-02-01', endDate: null },
  { developerId: 'dev-carla', projectId: 'project-devgraph', role: 'Graph Architect', startDate: '2022-11-01', endDate: null },
  { developerId: 'dev-carla', projectId: 'project-marketpulse', role: 'Data Architect', startDate: '2020-04-01', endDate: '2022-01-15' },
  { developerId: 'dev-david', projectId: 'project-healthsync', role: 'ML Engineer', startDate: '2023-03-01', endDate: null },
  { developerId: 'dev-elena', projectId: 'project-marketpulse', role: 'Cloud Engineer', startDate: '2021-01-10', endDate: '2022-01-15' },
  { developerId: 'dev-elena', projectId: 'project-healthsync', role: 'DevOps Engineer', startDate: '2023-01-01', endDate: null },
  { developerId: 'dev-farah', projectId: 'project-billwise', role: 'Backend Engineer', startDate: '2023-04-01', endDate: null },
  { developerId: 'dev-gabriel', projectId: 'project-fleettrack', role: 'Lead Architect', startDate: '2022-01-01', endDate: null },
  { developerId: 'dev-hana', projectId: 'project-eduspark', role: 'Frontend Engineer', startDate: '2023-06-01', endDate: null },
  { developerId: 'dev-isabella', projectId: 'project-marketpulse', role: 'Data Engineer', startDate: '2021-05-01', endDate: '2022-01-15' },
  { developerId: 'dev-jamal', projectId: 'project-eduspark', role: 'Junior Frontend Engineer', startDate: '2024-01-01', endDate: null },
  { developerId: 'dev-kavya', projectId: 'project-fleettrack', role: 'Cloud Engineer', startDate: '2022-03-01', endDate: null },
  { developerId: 'dev-liam', projectId: 'project-devgraph', role: 'Principal Engineer', startDate: '2022-09-01', endDate: null },
  { developerId: 'dev-liam', projectId: 'project-payflow', role: 'Architect', startDate: '2020-01-01', endDate: '2021-12-31' },
  { developerId: 'dev-maya', projectId: 'project-healthsync', role: 'ML Lead', startDate: '2023-02-01', endDate: null },
  { developerId: 'dev-noah', projectId: 'project-billwise', role: 'DevOps Engineer', startDate: '2023-05-01', endDate: null },
  { developerId: 'dev-olivia', projectId: 'project-fleettrack', role: 'Cloud Architect', startDate: '2022-01-15', endDate: null },
  { developerId: 'dev-olivia', projectId: 'project-marketpulse', role: 'Cloud Consultant', startDate: '2021-06-01', endDate: '2022-01-15' },
]

export const workedAtRelationships: WorkedAtRelationship[] = [
  { developerId: 'dev-alice', companyId: 'company-acme', role: 'Senior Frontend Engineer', startDate: '2021-01-01', endDate: null },
  { developerId: 'dev-brian', companyId: 'company-acme', role: 'Backend Engineer', startDate: '2022-06-01', endDate: null },
  { developerId: 'dev-carla', companyId: 'company-initech', role: 'Principal Engineer', startDate: '2018-09-01', endDate: null },
  { developerId: 'dev-david', companyId: 'company-umbrella', role: 'ML Engineer', startDate: '2023-01-01', endDate: null },
  { developerId: 'dev-elena', companyId: 'company-globex', role: 'Cloud Architect', startDate: '2020-05-01', endDate: null },
  { developerId: 'dev-farah', companyId: 'company-nimbus', role: 'Backend Engineer', startDate: '2023-01-01', endDate: null },
  { developerId: 'dev-gabriel', companyId: 'company-initech', role: 'Lead Architect', startDate: '2019-03-01', endDate: null },
  { developerId: 'dev-hana', companyId: 'company-acme', role: 'Frontend Engineer', startDate: '2023-04-01', endDate: null },
  { developerId: 'dev-isabella', companyId: 'company-umbrella', role: 'Data Engineer', startDate: '2020-01-01', endDate: null },
  { developerId: 'dev-jamal', companyId: 'company-acme', role: 'Junior Engineer', startDate: '2024-01-01', endDate: null },
  { developerId: 'dev-kavya', companyId: 'company-nimbus', role: 'Cloud Engineer', startDate: '2021-08-01', endDate: null },
  { developerId: 'dev-liam', companyId: 'company-globex', role: 'Principal Engineer', startDate: '2017-01-01', endDate: null },
  { developerId: 'dev-maya', companyId: 'company-umbrella', role: 'ML Lead', startDate: '2022-06-01', endDate: null },
  { developerId: 'dev-noah', companyId: 'company-nimbus', role: 'DevOps Engineer', startDate: '2022-01-01', endDate: null },
  { developerId: 'dev-olivia', companyId: 'company-nimbus', role: 'Cloud Architect', startDate: '2019-05-01', endDate: null },
]

export const usesRelationships: UsesRelationship[] = [
  { projectId: 'project-devgraph', technologyId: 'tech-typescript', usage: 'primary' },
  { projectId: 'project-devgraph', technologyId: 'tech-nextjs', usage: 'primary' },
  { projectId: 'project-devgraph', technologyId: 'tech-neo4j', usage: 'primary' },
  { projectId: 'project-devgraph', technologyId: 'tech-nodejs', usage: 'secondary' },
  { projectId: 'project-payflow', technologyId: 'tech-python', usage: 'primary' },
  { projectId: 'project-payflow', technologyId: 'tech-postgresql', usage: 'primary' },
  { projectId: 'project-payflow', technologyId: 'tech-aws', usage: 'secondary' },
  { projectId: 'project-healthsync', technologyId: 'tech-python', usage: 'primary' },
  { projectId: 'project-healthsync', technologyId: 'tech-postgresql', usage: 'secondary' },
  { projectId: 'project-healthsync', technologyId: 'tech-aws', usage: 'primary' },
  { projectId: 'project-marketpulse', technologyId: 'tech-react', usage: 'primary' },
  { projectId: 'project-marketpulse', technologyId: 'tech-nodejs', usage: 'primary' },
  { projectId: 'project-marketpulse', technologyId: 'tech-aws', usage: 'secondary' },
  { projectId: 'project-shoplite', technologyId: 'tech-react', usage: 'primary' },
  { projectId: 'project-shoplite', technologyId: 'tech-nodejs', usage: 'secondary' },
  { projectId: 'project-fleettrack', technologyId: 'tech-python', usage: 'primary' },
  { projectId: 'project-fleettrack', technologyId: 'tech-postgresql', usage: 'primary' },
  { projectId: 'project-fleettrack', technologyId: 'tech-docker', usage: 'secondary' },
  { projectId: 'project-fleettrack', technologyId: 'tech-aws', usage: 'secondary' },
  { projectId: 'project-eduspark', technologyId: 'tech-react', usage: 'primary' },
  { projectId: 'project-eduspark', technologyId: 'tech-nodejs', usage: 'primary' },
  { projectId: 'project-eduspark', technologyId: 'tech-graphql', usage: 'secondary' },
  { projectId: 'project-billwise', technologyId: 'tech-python', usage: 'primary' },
  { projectId: 'project-billwise', technologyId: 'tech-postgresql', usage: 'primary' },
  { projectId: 'project-billwise', technologyId: 'tech-docker', usage: 'primary' },
]

export const skillRelatedToRelationships: SkillRelatedToRelationship[] = [
  { fromSkillId: 'skill-frontend-dev', toSkillId: 'skill-ui-ux', strength: 0.7 },
  { fromSkillId: 'skill-backend-dev', toSkillId: 'skill-api-design', strength: 0.8 },
  { fromSkillId: 'skill-backend-dev', toSkillId: 'skill-system-design', strength: 0.75 },
  { fromSkillId: 'skill-graph-databases', toSkillId: 'skill-data-modeling', strength: 0.85 },
  { fromSkillId: 'skill-data-modeling', toSkillId: 'skill-machine-learning', strength: 0.6 },
  { fromSkillId: 'skill-cloud-architecture', toSkillId: 'skill-devops', strength: 0.8 },
  { fromSkillId: 'skill-api-design', toSkillId: 'skill-system-design', strength: 0.65 },
]

export const technologyRelatedToRelationships: TechnologyRelatedToRelationship[] = [
  { fromTechnologyId: 'tech-typescript', toTechnologyId: 'tech-react', strength: 0.8 },
  { fromTechnologyId: 'tech-typescript', toTechnologyId: 'tech-nextjs', strength: 0.85 },
  { fromTechnologyId: 'tech-nextjs', toTechnologyId: 'tech-react', strength: 0.9 },
  { fromTechnologyId: 'tech-nodejs', toTechnologyId: 'tech-typescript', strength: 0.75 },
  { fromTechnologyId: 'tech-nodejs', toTechnologyId: 'tech-nextjs', strength: 0.6 },
  { fromTechnologyId: 'tech-postgresql', toTechnologyId: 'tech-neo4j', strength: 0.4 },
  { fromTechnologyId: 'tech-aws', toTechnologyId: 'tech-postgresql', strength: 0.5 },
  { fromTechnologyId: 'tech-aws', toTechnologyId: 'tech-neo4j', strength: 0.5 },
  { fromTechnologyId: 'tech-docker', toTechnologyId: 'tech-aws', strength: 0.7 },
  { fromTechnologyId: 'tech-docker', toTechnologyId: 'tech-postgresql', strength: 0.4 },
  { fromTechnologyId: 'tech-graphql', toTechnologyId: 'tech-nodejs', strength: 0.6 },
  { fromTechnologyId: 'tech-graphql', toTechnologyId: 'tech-typescript', strength: 0.5 },
]
